apollo:
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: application,smy.constant,dubbo_common,redis,jdbc,ticket,mq
    eagerLoad:
      enabled: true

app:
  id: tfs-boot
  env: ${env}

# 项目相关配置
tfs:
  # 名称
  name: SMY
  # 版本
  version: 3.8.5
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/tfs/uploadPath，Linux配置 /home/tfs/uploadPath）
  profile: D:/tfs/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 11750
  servlet:
    # 应用的访问路径
    context-path: /tfs-api
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 20MB
      # 设置总上传的文件大小
      max-request-size: 60MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # kafka
  kafka:
    bootstrap-servers: 192.168.225.11:9092,192.168.225.12:9092,192.168.225.13:9092
    consumer: # 消费者
      group-id: tfs-group # 消费组
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      listener:
        ack-mode: MANUAL_IMMEDIATE
        concurrency: 4

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 480

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.smy.tfs.**.domain,com.smy.tfs.**.dbo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

mybatis-plus:
  # 搜索指定枚举
  typeEnumsPackage: com.smy.tfs.api.enums
  # 搜索指定包别名
  typeAliasesPackage: com.smy.tfs.**.domain,com.smy.tfs.**.dbo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /tfs-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

static-locations: [ "classpath:/static/", "classpath:/public/","classpath:/mapper/"," classpath:/META-INF/resources/","classpath:/resources/"]


