package com.smy.tfs.api.enums;

import com.smy.framework.base.UniqueIdCode;

import java.io.Serializable;

public enum TFSTableIdCode implements UniqueIdCode, Serializable {
    ID_TICKET_DATA("100", "SEQ_TICKET_DATA"),
    ID_TICKET_ACCOUNT("101", "SEQ_TICKET_ACCOUNT"),
    ID_TICKET_ANALYSIS_DATA("102", "SEQ_TICKET_ANALYSIS_DATA"),
    ID_TICKET_APP("103", "SEQ_TICKET_APP"),
    ID_TICKET_EXECUTOR_GROUP("104", "SEQ_TICKET_EXECUTOR_GROUP"),
    ID_TICKET_FLOW_DATA("105", "SEQ_TICKET_FLOW_DATA"),
    ID_TICKET_FLOW_EVENT_TEMPLATE("106", "SEQ_TICKET_FLOW_EVENT_TEMPLATE"),
    ID_TICKET_FLOW_NODE_APPROVE_DETAIL("107", "SEQ_TICKET_FLOW_NODE_APPROVE_DETAIL"),
    ID_TICKET_FLOW_NODE_DATA("108", "SEQ_TICKET_FLOW_NODE_DATA"),

    ID_TICKET_FLOW_NODE_EXECUTOR_DATA("109", "SEQ_TICKET_FLOW_NODE_EXECUTOR_DATA"),
    ID_TICKET_FLOW_NODE_EXECUTOR_TEMPLATE("110", "SEQ_TICKET_FLOW_NODE_EXECUTOR_TEMPLATE"),
    ID_TICKET_FLOW_NODE_RULE_TEMPLATE("111", "SEQ_TICKET_FLOW_NODE_RULE_TEMPLATE"),
    ID_TICKET_FLOW_NODE_TEMPLATE("112", "SEQ_TICKET_FLOW_NODE_TEMPLATE"),
    ID_TICKET_FLOW_TEMPLATE("113", "SEQ_TICKET_FLOW_TEMPLATE"),
    ID_TICKET_FORM_DATA("114", "SEQ_TICKET_FORM_DATA"),
    ID_TICKET_FORM_ITEM_DATA("115", "SEQ_TICKET_FORM_ITEM_DATA"),
    ID_TICKET_FORM_ITEM_TEMPLATE("116", "SEQ_TICKET_FORM_ITEM_TEMPLATE"),

    ID_TICKET_FORM_TEMPLATE("117", "SEQ_TICKET_FORM_TEMPLATE"),

    ID_TICKET_TEMPLATE("118", "SEQ_TICKET_TEMPLATE"),
    ID_TICKET_ACCOUNT_MAPPING_LACK("120", "SEQ_TICKET_ACCOUNT_MAPPING_LACK"),

    ID_TICKET_FLOW_EVENT_DATA("121", "SEQ_ID_TICKET_FLOW_EVENT_DATA"),

    TICKET_FORM_ITEM_ID_COL_MAPPING("122", "SEQ_TICKET_FORM_ITEM_ID_COL_MAPPING"),

    TICKET_FORM_ITEM_VALUES("123", "TICKET_FORM_ITEM_VALUES"),
    ID_TICKET_CONFIG("124", "SEQ_TICKET_CONFIG"),

    ID_TICKET_FLOW_NODE_ACTION_DATA("125", "ID_TICKET_FLOW_NODE_ACTION_DATA"),
    ID_TICKET_FLOW_NODE_ACTION_TEMPLATE("126", "ID_TICKET_FLOW_NODE_ACTION_TEMPLATE"),

    ID_TICKET_SLA_TEMPLATE("127", "ID_TICKET_SLA_TEMPLATE"),
    ID_TICKET_SLA_CONFIG_TEMPLATE("128", "ID_TICKET_SLA_CONFIG_TEMPLATE"),

    ;

    //max 126
    private String code;
    private String sequenceName;

    private TFSTableIdCode(String code, String sequenceName) {
        this.code = code;
        this.sequenceName = sequenceName;
    }

    public String getCode() {
        return this.code;
    }

    public String getSequenceName() {
        return this.sequenceName;
    }
}